version: '3.8'

services:
  php:
    build:
      context: ./docker/php/
      args:
        PHP_VERSION: "${PHP_VERSION}"
    restart: always
    volumes:
      - "./:/var/www/html"
      - "./config/php/php-${PHP_ENVIRONMENT}.ini:/usr/local/etc/php/conf.d/php.ini"
    command: /bin/sh -c "composer install && php-fpm"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - "./:/var/www/html"
      - "./config/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    healthcheck:
      test: curl --fail http://localhost || exit 1
    expose:
      - 80
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php

networks:
  proxiable:
    external: true